In [ ]:
#Schema Star :
SELECT
dim_store.store_address,

SUM(fact_sales.quantity) ASquantity_sold


FROM

fact_sales

INNERJOINdim_product ONfact_sales.product_id = dim_product.product_id

INNERJOINdim_time ONfact_sales.time_id = dim_time.time_id

INNERJOINdim_store ONfact_sales.store_id = dim_store.store_id

 
WHERE

dim_time.action_year = 2016

ANDdim_store.city = ‘Berlin’

ANDdim_product.product_type = ‘phone’

 

GROUPBY

dim_store.store_id,

dim_store.store_address

#Query ini akan menampilkan tabel fakta yang akan menampilkan data  jalan dan total quantity yang terjual dari 3 tabel dimensi yang berbeda yaitu tabel dimensi produk, time, dan store dimana kondisinya adalah pada tahun 2016 dengan nama kota berlin dan produknya adalah handphone yang akan diurutkan berdasarkan store_id dan store_adress.

In [ ]:
#Schema Snowflake :
SELECT

  dim_store.store_address,
  SUM(fact_sales.quantity) ASquantity_sold

FROM

  fact_sales

  INNERJOINdim_product ONfact_sales.product_id = dim_product.product_id

  INNERJOINdim_product_type ONdim_product.product_type_id = dim_product_type.product_type_id

  INNERJOINdim_time ONfact_sales.time_id = dim_time.time_id

  INNERJOINdim_year ONdim_time.year_id = dim_year.year_id

  INNERJOINdim_store ONfact_sales.store_id = dim_store.store_id

  INNERJOINdim_city ONdim_store.city_id = dim_city.city_id

WHERE

  dim_year.action_year = 2016

  ANDdim_city.city = ‘Berlin’

  ANDdim_product_type.product_type_name = ‘phone’

GROUPBY

  dim_store.store_id,

  dim_store.store_address


#Query ini akan menampilkan data yang sama seperti Schema Bintang(Star) hanya saja lebih kompleks karena memiliki lebih banyak tabel karena sudah dinormalisasi sebelumnya.